FROM nginx
# https://registry.hub.docker.com/_/nginx/

# Apply our Nginx configuration
ADD config/default.conf /etc/nginx/conf.d/default.conf


# inspiration: 
# https://github.com/dylanlindgren/docker-nginx
