FROM nginx

# COPY webapp /usr/share/nginx/html
# fastcgi_pass unix:/var/run/php5-fpm.sock;
# replace with 
# fastcgi_pass 127.0.0.1:9000;
#  /etc/nginx/nginx.conf

# RUN sed -i '/^listen /c \
# listen = 0.0.0.0:9000' /etc/nginx/nginx.conf
